name: az4
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - torchvision=0.17.0
  - pip
  - pip:
      - pytorch-lightning==2.2.0
      - numpy==1.26.4
      - pandas==2.2.2
      - typing-extensions==4.11.0
